name: Upload Video to YouTube

on:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  upload_video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Remplacez par la version de Python que vous utilisez

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Python script
        run: python upload_script.py  # Remplacez par le nom de votre script Python
        env:
          API_KEY: ${{ secrets.API_KEY }}  # Ajoutez votre clé API comme secret dans les paramètres du repository
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}  # Ajoutez votre CHANNEL_ID comme secret dans les paramètres du repository
